export const StartNavigation: string = "StartNavigation"

export const StartPage: string = 'StartApp'

export const PreferredPage: string = 'PreferredPage'

export const LogInPage: string = "LogInPage"

export const RegisterPage: string = "RegisterPage"

export const LayOutPage: string = "LayOutPage"

export const SettingPage: string = "SettingPage"

export const PersonInfoPage: string = "PersonInfoPage"

export const AddressMangePage: string = "AddressMangePage"

export const AccountSafePage: string = "AccountSafePage"

export const DeliveryAddressPage: string = "DeliveryAddressPage"

export const ReturnAddressPage: string = "ReturnAddressPage"

export const PersonalHomePage: string = "PersonalHomePage"

export const PersonInfoSetting: string = "PersonInfoSetting"

export const SearchHistoryPage: string = "SearchHistoryPage"

export const ProductDetailPage: string = "ProductDetailPage"

export const ShopDetailPage: string = "ShopDetailPage"

export const UserNameSetting: string = "UserNameSettingPage"

export const UserIntroductionSetting: string = "UserIntroductionSettingPage"

export const ProductCollectPage: string = "ProductCollectPage"

export const ShopFollowPage: string = "ShopFollowPage"

export const ViewHistoryPage: string = "ViewHistoryPage"

export const ShoppingCartPage: string = "ShoppingCartPage"