export class Constants{
  static readonly FULL_PERCENT: string = '100%';
  static readonly TAB_CONTENT_HEIGHT: number = 60;
  static readonly MAX_LINES: number = 1;
  static readonly LIST_SPACE: number = 10;
  static readonly GRADIENT_ANGLE = 90;
  static readonly FONT_WEIGHT: number = 400;
  static readonly ZERO_INDEX: number = 0;
  static readonly ONE_INDEX: number = 1;
  static readonly TWO_INDEX: number = 2;
  static readonly ZERO_LENGTH: number = 0;
  static readonly NUM_ONE = 1;
  static readonly MINUS_ONE = -1;
  static readonly TAB_ANIMATION_DURATION = 400;
  static readonly NORMAL_COLOR = '#000000';
  static readonly SELECT_COLOR = '#E84026';
  static readonly GRADIENT_GRAY = '#F4F6F7';
  static readonly GRADIENT_RED = '#fef5f5';
  static readonly GRADIENT_WHITE = '#ffffff';
  static readonly GRADIENT_START = 0.5;
  static readonly GRADIENT_END = 1.0;
  static readonly INITIAL_VALUE = 0;
  static  SEARCH_DATA: string[] = [
    '手机',
    '手机华为',
    '手机苹果',
    '手机小米',
    '手机vivo',
    '手机oppo',
    '手机荣耀',
    '手机折叠屏',
    '手机稳定器',
    '手机支架',
    '手机壳',
    '手机散热器',
    '手机华为mate60',
    '手机华为mate60',
    '手机华为mate60',
    '手机华为mate60'
  ]
}
